config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  root 'homes#top'
  get 'homes/about'
  resources :photos
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  resources :users do
    get :search, on: :collection
  end
  resources :users do
    resources :favorites
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
    resources :likes
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following

  has_many :photos, -> { order('created_at DESC') }, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image
  validates :name, presence: true
  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

  def liked_by?(photo_id)
    likes.where(photo_id: photo_id).exists?
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :ensure_normal_user, only: %i(update destroy)

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :ensure_normal_user, only: :destroy

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.where.not(id: current_user.id)
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    elsif @user.update(params.require(:user).permit(:name, :email, :image))
      flash[:notice] = "アカウント情報を更新しました"
      redirect_to user_path(id: current_user.id)
    else
      render "edit"
    end
  end

  def search
    if params[:name].present?
      @users = User.where('name LIKE ?', "%#{params[:name]}%")
    else
      @users = User.none
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<table class="table text-center">
<thead>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>
</thead>
<tbody>
  <% @users.each do |user| %>
    <tr>
      <td>
        <%= link_to user_path(user) do %>
          <%= user.name %>
        <% end %>
      </td>
      <td>
        <% if user != current_user %>
          <% if user.is_followed_by?(current_user) %>
            <%=link_to user_relationships_path(user), method: :delete do %>
              <button type="button" class="btn btn btn-danger">フォロー解除</button>
            <% end %>
          <% else %>
            <%=link_to user_relationships_path(user), method: :post do %>
              <button type="button" class="btn btn btn-primary">フォロー</button>
            <% end %>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/users/_mytimeline.html.erb
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 g-4">
  <% @user.photos.each do |photo|%>
    <div class="col-12">
      <div class="mx-auto card h-100 text-dark bg-light border-dark mb-3" style="max-width: 18rem;">
        <% if photo.user.image.attached? %>
          <%= image_tag photo.user.image, class: "mx-auto rounded-circle", size: "80x80"  %>
        <% else %>
          <svg width="80" height="80" class="card-img-top" viewBox="0 0 20 20">
            <path d="M12.075,10.812c1.358-0.853,2.242-2.507,2.242-4.037c0-2.181-1.795-4.618-4.198-4.618S5.921,4.594,5.921,6.775c0,1.53,0.884,3.185,2.242,4.037c-3.222,0.865-5.6,3.807-5.6,7.298c0,0.23,0.189,0.42,0.42,0.42h14.273c0.23,0,0.42-0.189,0.42-0.42C17.676,14.619,15.297,11.677,12.075,10.812 M6.761,6.775c0-2.162,1.773-3.778,3.358-3.778s3.359,1.616,3.359,3.778c0,2.162-1.774,3.778-3.359,3.778S6.761,8.937,6.761,6.775 M3.415,17.69c0.218-3.51,3.142-6.297,6.704-6.297c3.562,0,6.486,2.787,6.705,6.297H3.415z"></path>
          </svg>
        <% end %>
        <div class="card-header bg-transparent border-dark text-center">
          <%= link_to photo.user.name, [photo.user], class:"card-title" %>
        </div>
        <div class="card-body text-secondary">
          <div class="card-title">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-map-pin"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/></svg>
            <% if photo.latitude.blank? %>
              <%= photo.address %>
            <% else %>
              <%= link_to photo.address, photo %>
            <% end %>
          </div>
          <div class="card-text">
            <%= photo.caption %>
            <% if current_user.liked_by?(photo.id) %>
              <%= link_to destroy_like_path(photo), method: :delete do %>
                <div class="myicon1">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path fill-rule="evenodd" d="M7.655 14.916L8 14.25l.345.666a.752.752 0 01-.69 0zm0 0L8 14.25l.345.666.002-.001.006-.003.018-.01a7.643 7.643 0 00.31-.17 22.08 22.08 0 003.433-2.414C13.956 10.731 16 8.35 16 5.5 16 2.836 13.914 1 11.75 1 10.203 1 8.847 1.802 8 3.02 7.153 1.802 5.797 1 4.25 1 2.086 1 0 2.836 0 5.5c0 2.85 2.045 5.231 3.885 6.818a22.075 22.075 0 003.744 2.584l.018.01.006.003h.002z"></path></svg>
                </div>
              <% end %>
            <% else %>
              <%= link_to create_like_path(photo), method: :post do %>
                <div class="myicon1">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path fill-rule="evenodd" d="M4.25 2.5c-1.336 0-2.75 1.164-2.75 3 0 2.15 1.58 4.144 3.365 5.682A20.565 20.565 0 008 13.393a20.561 20.561 0 003.135-2.211C12.92 9.644 14.5 7.65 14.5 5.5c0-1.836-1.414-3-2.75-3-1.373 0-2.609.986-3.029 2.456a.75.75 0 01-1.442 0C6.859 3.486 5.623 2.5 4.25 2.5zM8 14.25l-.345.666-.002-.001-.006-.003-.018-.01a7.643 7.643 0 01-.31-.17 22.075 22.075 0 01-3.434-2.414C2.045 10.731 0 8.35 0 5.5 0 2.836 2.086 1 4.25 1 5.797 1 7.153 1.802 8 3.02 8.847 1.802 10.203 1 11.75 1 13.914 1 16 2.836 16 5.5c0 2.85-2.045 5.231-3.885 6.818a22.08 22.08 0 01-3.744 2.584l-.018.01-.006.003h-.002L8 14.25zm0 0l.345.666a.752.752 0 01-.69 0L8 14.25z"></path></svg>
                </div>
              <% end %>
            <% end %>
            <%= photo.likes.count %>
            <% if photo.image.attached? %>
              <%= image_tag photo.image, class:"card-img-bottom"%>
            <% end %>
          </div>
        </div>
        <div class="card-footer border-dark">
          <%= photo.created_at.to_s(:datetime_jp) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="row mt-5">
  <div class="col-6 offset-3">
    <h3 class="text-center mb-4">ユーザー編集</h3>
     
    <%= form_with model: @user do |f| %>
      <div class="form-group mb-4">
        <%= f.label :name ,"名前" %><br />
        <%= f.text_field :name, class: "form-control form-control-lg" %>
      </div>
      <div class="form-group mb-4">
        <%= f.label :image ,"アイコン" %><br />
        <%= f.file_field :image, class: "form-control form-control-lg" %>
      </div>
      <div>
      <div class="actions">
        <%= f.submit "更新" , class: "btn btn-lg btn-primary btn-block mb-3" %>
      </div>
    <% end %>
    <%= link_to "マイページへ戻る", "/users/#{current_user.id}" %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <h1>FOLLOWERS</h1>
      <%= render 'users/list' %>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <h1>FOLLOWING</h1>
      <%= render 'users/list' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <%= form_with url: search_users_path, method: :get, local: true do |f| %>
        <%= f.text_field :name, :placeholder => "Name検索", id: 'search_name' %>
        <%= f.submit :検索 %>
      <% end %>
      <%= render 'users/list' %>
    </div>
  </div>
</div>

app/views/users/search.html.erb
<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <%= form_with url: search_users_path, method: :get, local: true do |f| %>
        <%= f.text_field :name, :placeholder => "Name検索" %>
        <%= f.submit :検索 %>
      <% end %>
      <%= render 'users/list' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <% if @user.image.attached? %>
        <%= image_tag @user.image, class: "rounded-circle", size: "150x150" %>
      <% else %>
        <svg width="80" height="80" class="svg-icon" viewBox="0 0 20 20">
          <path d="M12.075,10.812c1.358-0.853,2.242-2.507,2.242-4.037c0-2.181-1.795-4.618-4.198-4.618S5.921,4.594,5.921,6.775c0,1.53,0.884,3.185,2.242,4.037c-3.222,0.865-5.6,3.807-5.6,7.298c0,0.23,0.189,0.42,0.42,0.42h14.273c0.23,0,0.42-0.189,0.42-0.42C17.676,14.619,15.297,11.677,12.075,10.812 M6.761,6.775c0-2.162,1.773-3.778,3.358-3.778s3.359,1.616,3.359,3.778c0,2.162-1.774,3.778-3.359,3.778S6.761,8.937,6.761,6.775 M3.415,17.69c0.218-3.51,3.142-6.297,6.704-6.297c3.562,0,6.486,2.787,6.705,6.297H3.415z"></path>
        </svg>
      <% end %>
      <h1 class="fw-light"><%= @user.name %></h1>
      <p class="text-small"><%= link_to @user.followings.count, followings_user_path(@user) %> フォロー <%= link_to @user.followers.count, followers_user_path(@user) %> フォロワー</p>
      <p class="text-small"><%= link_to 'いいねした投稿', [@user, :likes] %></p>
      <% if @user == current_user %>
        <p class="lead text-muted">You're currently signed in as <%= current_user.email %></p>
      <% else %>
        <% if user_signed_in? %>
          <% if @user.is_followed_by?(current_user) %>
            <%=link_to user_relationships_path(@user), method: :delete do %>
              <button type="button" class="btn btn btn-danger">フォロー解除</button>
            <% end %>
          <% else %>
            <%=link_to user_relationships_path(@user), method: :post do %>
              <button type="button" class="btn btn btn-primary">フォロー</button>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</section>
<div class="container">
  <div class="row">
    <%= render 'users/mytimeline' %>
  </div>
</div>